### ISSUE TITLE
[Error] crash in only 'prod' environment: you have requested a non-existent parameter "container.build_id".

### ISSUE THREAD

**Issue by nickicool** [atom-php/uploader-bundle#10]
I tried to publish my site on the production server. Installed the environment in APP_ENV=prod, and the site did not start. An error is displayed:

> (1/1) ParameterNotFoundException: You have requested a non-existent parameter "container.build_id". in ParameterBag.php line 100

Аfter 2 days of searching what can cause a crash, I found this bundle. I don't know why this causes an error in the 'prod' environment, but the console also stops working. In 'dev' environment all works fine!

To reproduce error, you can simply clone the Symfony Demo application, and install `composer require atom-php/uploader-bundle`. No additional configuration is needed - just install the bundle and delete the 'prod' Symfony cache directory.

2 methods help to fix the error: 
- comment out the line `Atom\UploaderBundle\AtomUploaderBundle:: class => ['all' => true]`, but it doesn't make sense - bundle cant works.
- and comment lines in `// config/packages/prod/doctrine.yaml`, but it works if caching is not used anywhere. The Demo application is used on post pages.

Trying few versions
- "atom-php/uploader-bundle": "^1.1@dev"
- "atom-php/uploader-bundle": "^1.0.8",

Used Symfony 4.1.8.

**Comment by sergey-uchvatov** [comment]
Same error with symfony 4 when I try to implement custom compiler pass. Reproduces only in prod environment
`$container->addCompilerPass(new CustomPass(), PassConfig::TYPE_AFTER_REMOVING);`
My workaround is just add default param in parameters.yaml
```
parameters:
    container.build_id: ~
```

**Comment by nickicool** [comment]
Yes, this work for me too!
Thank you!
