### ISSUE TITLE
Есть ли возможность не удалять Entity, если не удается удалить привязанные к нему фаилы?

### ISSUE THREAD

**Issue by nickicool** [atom-php/uploader-bundle#9]
Как ни будь можно не удалять запись Entity из БД, если привязанные фаилы невозможно удалить физически с диска, например, нет прав? Попробовал сделать через эвенты бандла (проверку доступности файлов опустил):
     
    class ImageUploadSubscriber implements EventSubscriberInterface
    {   
        public static function getSubscribedEvents()
        {
            return [
                IUploadEvent::PRE_REMOVE => 'handleDelete',
                IUploadEvent::PRE_REMOVE_OLD_FILE => 'handleDelete',
            ];
        }
    
        public function handleDelete(UploadEvent $event)
        {
            $event->stopPropagation();
            $event->stopAction();
            return false;
         }
    }

Этот вариант отменяет удаление файлов (файлы остаются на диске), но процесс удаления Entity не отменяется и запись удаляется. Или это нужно реализовать как эвент доктрины, а не этого бандла?

**Comment by nickicool** [comment]
Кстати, отдельное спасибо за отличный бандл. Особенно радует то, что можно сохранять имя фаила вместе с путем - очень удобно. Остальные бандлы почему то все предлагают путь генерировать на лету, что по мне очень неудобно и излишне, ибо менять расположение фаилов требуется очень и очень редко, и лишняя логика по вычислению пути - ну такое себе.

**Comment by hippy-azimov** [comment]
Здравствуйте, достаточно прервать удаление сущности, на эвент доктрины(preRemove).

> если привязанные фаилы невозможно удалить физически с диска, например, нет прав?

```php
<?php declare(strict_types=1);

use Atom\Uploader\Filesystem\FilesystemAdapterRepo;
use Atom\Uploader\Handler\PropertyHandler;
use Atom\Uploader\Handler\UploadHandler;
use Atom\Uploader\Metadata\MetadataRepo;
use Doctrine\Common\EventSubscriber;
use Doctrine\ORM\Event\LifecycleEventArgs;
use Doctrine\ORM\Events;

class ImageSubscriber implements EventSubscriber
{
    /**
     * @var UploadHandler
     */
    private $uploadHandler;
    /**
     * @var MetadataRepo
     */
    private $metadataRepo;
    /**
     * @var PropertyHandler
     */
    private $propertyHandler;
    /**
     * @var FilesystemAdapterRepo
     */
    private $filesystemAdapterRepo;

    public function __construct(
        UploadHandler $uploadHandler,
        MetadataRepo $metadataRepo,
        PropertyHandler $propertyHandler,
        FilesystemAdapterRepo $filesystemAdapterRepo
    ) {
        $this->uploadHandler = $uploadHandler;
        $this->metadataRepo = $metadataRepo;
        $this->propertyHandler = $propertyHandler;
        $this->filesystemAdapterRepo = $filesystemAdapterRepo;
    }

    public function preRemove(LifecycleEventArgs $args): void
    {
        $entity = $args->getEntity();
        if (!$this->metadataRepo->hasMetadata($entity)) {
            // Сущность не управляется бандлом, пропустим.
            return;
        }

        // Получаем путь к файлу
        $metadata = $this->metadataRepo->getMetadata($entity);
        $path = (string)$this->propertyHandler->getFile($entity, $metadata);
        // Получаем файл, резолвиться именно информация о файле(SplFileInfo), никаких проверок не проводиться.
        $filesystem = $this->filesystemAdapterRepo->getFilesystem($metadata->getFsAdapter());
        $fileInfo = $filesystem->resolveFileInfo($metadata->getFsPrefix(), $path);
        if (false === $fileInfo->isWritable()) {
            // Можно прервать удаление сущности.
            $args->getEntityManager()->detach($entity);
        }
    }

    public function getSubscribedEvents(): array
    {
        return [
            Events::preRemove,
        ];
    }
}
```

**Comment by nickicool** [comment]
Да, я пробовал и `vich/uploader-bundle` - он тоже в поле БД сохраняет только имя фаила - все пути отсекаются на этапе сохранения в БД, даже если нейминг фаила генерирует имя фаила с путем. Поэтому путь приходится генерировать каждый раз при выводе фаила. А с твоим бандлом я уже в БД могу сохранить абсолютный путь, аля `"/path/to/filename.jpg"` и выводить фаил картинки простым `<img src={{ image.imageFile }}>`, а не что то типа `<img src={{ path ~ image.imageFile }}>`, тем более что путь нужен разный, даже у разных галерей. 

Возможно я не вижу подводных камней, но я часто работаю с картинками, и менять их местоположение в структуре файловой системы необходимо, ну.... очень, очень редко. Так зачем тогда каждый раз генерировать путь, если его проще сразу сохранить вместе с именем файла.))

За помощь с отменой удаления - отдельное спасибо, попробую сегодня/завтра! Правда у меня немного по другому получилось сделать. Буду благодарен за советы:

    public function preRemove(LifecycleEventArgs $args)
    {
        $entity = $args->getEntity();
        if (!$entity instanceof Image) {
            return;
        }

        $files = $this->getFiles($entity);
        foreach ($files as $file) {
            try {
                $this->filesystem->remove($file);
            } catch (IOException $exception) {
                // Cancel removal
                throw $exception;
            }
        }
    }
    
    private function getFiles(Image $entity)
    {
        return [
            $this->webRootDir . $entity->getImageFile(),
            $this->webRootDir . $entity->getPreviewFile(),
        ];
    }

И да, тут мне надо удалить не только imageFile, который обрабатывается atom-php/uploader-bundle, но и previewFile, который генерирует liip/imagine-bundle:

    // Image entity
    /**
     * Тут сохраняется /path/filename.jpg основной картинки
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $imageFile;

    /**
     * Тут сохраняется /path/filename.jpg превьюшки картинки
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $previewFile;

    // config
    atom_uploader:
        driver:
            - orm
        mappings:
            App\Entity\Image:
                file_setter: imageFile
                file_getter: imageFile

**Comment by nickicool** [comment]
И контроллер забыл добавить

    public function delete(Image $image, Request $request): Response
    {
        if (!$this->isCsrfTokenValid('delete', $request->request->get('token'))) {
            return new Response('Error');
        }

        $em = $this->getDoctrine()->getManager();
        try {
            $em->remove($image);
            $this->addFlash('success', 'image.deleted_successfully');
        } catch (\Exception $exception) {
            $this->addFlash('error', $exception->getMessage());
        }
        $em->flush();

        return new Response('OK');
    }

**Comment by nickicool** [comment]
И еще, я знаю что есть такой параметр как 

    # Если true то после удаления данных файл тоже удаляется.
    delete_on_remove: true

Но, мне нужно удалять и превьюшку, а ее удалением бандл не управляет. Поэтому и основную картинку приходится удалять "руками", чтобы был единый стиль.

**Comment by nickicool** [comment]
Понимаю, что все наверное через одно место, но я не профессионал, и с учетом своих требований к проекту, реализовал как смог. Требования такие:
- путь сохранять вместе с именем фаила, ибо мне так проще и понятнее, и не нужны дополнительные свойства и методы у сущности для генерации пути.
- путь может быть разным ибо картинки раскидываю по папкам именованным текущей датой, аля "/gallery/id/2018-07/filename.jpg" (чтобы не все в одну, ибо много фаилов потом усложняет работу с фаиловой системой - тормозит при открытии папки)
- фаилов два: картинка и превьюшка, и пути к обеим хранить в БД. Необходимость хранить в сущности и путь к превьюшке, а значит и генерировать/удалять ее, послужили препятствием к использованию таких штук твоего бандла как:

            # Если true то после удаления данных файл тоже удаляется.
            delete_on_remove: false

            # Если true то при загрузке данных внедряется URI
            inject_uri_on_load: false
